schema_version = "1.0.0"
id = "camerafly"
version = "2.1.2"
name = "Camerafly"
tagline = "Fly around with the Dolly Rig of the Camera Rigs Addon"
maintainer = "Michael Schieber <mail@michaelschieber.de>"
type = "add-on"
website = "https://linktr.ee/MichaelSchieber"

tags = ["Camera"]
blender_version_min = "4.2.0"
license = [
    "SPDX:GPL-3.0-or-later"
]

wheel-path = "./wheels"

[build]
source = "./camera_fly"
build = "./extension_build_dir/build"
dist = "./extension_build_dir/dist"
paths = [
    'LICENSE',
    'README.md',
]
paths_exclude_pattern = [
    "__pycache__/",
    "/.git/",
    "/*.zip",
]